### ISSUE TITLE
Wrap NFT request

### ISSUE THREAD

**Issue by cariawmetis** [MetisProtocol/nftbridge#1]
Native NFT chainid (Andromeda 1088, Stardust 588, Ethereum 1, Rinkeby 4):4
Native NFT contract address: 0x719883E1985753D6b2d65774ed3B11f7aA632C4c
Deployed wrap NFT contract address:0x78a1a10c242e0de3ebb67c4eb47ca8b709b7e032
Transaction hash of the contract deployment:10,11

**Comment by 54meteor** [comment]
Already added
