### ISSUE TITLE
Wrap NFT request

### ISSUE THREAD

**Issue by cariawmetis** [MetisProtocol/nftbridge#2]
Native NFT chainid (Andromeda 1088, Stardust 588, Ethereum 1, Rinkeby 4):588
Native NFT contract address:0x6babD8ABFB079039bf53A032CBe5EFEc63b692E6
Deployed wrap NFT contract address: 0xc286a3177a2aa16f3061c742cf230c6f361484b9
Transaction hash of the contract deployment:10.11

**Comment by 54meteor** [comment]
Already added
