### ISSUE TITLE
Wrap NFT request

### ISSUE THREAD

**Issue by CryptoSavvy23** [MetisProtocol/nftbridge#3]
Native NFT chainid (Andromeda 1088, MetisBoredApe 7282, Ethereum 1, Rinkeby 4):
Native NFT contract address:0xB6C13bB8f4f83a3bA87c9b20066bCf98a9319444
Deployed wrap NFT contract address:0xf85a7e967705b2efe80f79287ae1bb76be2d77c0
Transaction hash of the contract deployment:

**Comment by CryptoSavvy23** [comment]
Metis BAYC is a collection of 10,000 NFTs living on Metis blockchain and derivative of the Famous NFT collectible ~ Bored Ape Yacht Club ~. We are here to declare Metis NFTs are the NEXT BIG THING. ! Not affiliated with Yuga Labs !

**Comment by bossyuansu** [comment]
working on it

**Comment by bossyuansu** [comment]
is the native contract 0xB6C13bB8f4f83a3bA87c9b20066bCf98a9319444 on andromeda and 0xf85a7e967705b2efe80f79287ae1bb76be2d77c0 on ethereum?

**Comment by CryptoSavvy23** [comment]
Yes

**Comment by bossyuansu** [comment]
done. happy bridging

**Comment by CryptoSavvy23** [comment]
Apologies I got the ETH address wrong. The correct ETH address is 0x535926b17b9df2CD132E1Ff123CB49DbF6FF1834

**Comment by bossyuansu** [comment]
0x535926b17b9df2CD132E1Ff123CB49DbF6FF1834  is not a contract address though

**Comment by CryptoSavvy23** [comment]
NFT Token Address(Andromeda) = 0xB6C13bB8f4f83a3bA87c9b20066bCf98a9319444
Receiver Address(Ethereum) = 0x535926b17b9df2CD132E1Ff123CB49DbF6FF1834
Token ID = 7282
NFT Token Standard = ERC721

**Comment by bossyuansu** [comment]
this request is to connect to the wrapped NFT contract address and the native NFT contract address. to actually bridge the NFT, you can use nftbridge.metis.io  here is the instruction https://docs.metis.io/metis-nft-bridge/bridge-nft
